# Generated by Django 4.1.7 on 2023-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default=1001, max_length=100),
            preserve_default=False,
        ),
    ]
