# Generated by Django 4.1.7 on 2023-03-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_uname_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
