# Generated by Django 4.1.7 on 2023-06-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='donner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
