# Generated by Django 4.1.7 on 2023-06-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_donner_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donner',
            name='created',
        ),
    ]
