# Generated by Django 4.1.7 on 2023-06-15 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_donner_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField()),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01234567899'. Up to 11 digits allowed.", regex='^\\+?1?\\d{11}$')])),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='profile_images')),
                ('bloodgroups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blood')),
                ('management_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.managementrole')),
            ],
        ),
    ]
