# Generated by Django 4.1.7 on 2023-06-15 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_managementrole_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01234567899'. Up to 11 digits allowed.", regex='^\\+?1?\\d{11}$')]),
        ),
    ]
