# Generated by Django 4.1.7 on 2023-06-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_management_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='bloodgroups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blood'),
        ),
    ]
